[package]
name = "model-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
easy-gltf = { git="https://github.com/chuigda/easy-gltf", branch="preserve_transform", features = ["names", "vertex-color"]}
cgmath = "0.18.0"
