error.lookAndFeelUnavailable=Error happened. Look and feel currently unavailable. Falling back to default.
ctrlpane.btn.additionOpt=Add. Opts
ctrlpane.btn.addon=Add-ons
ctrlpane.btn.attCtrl=Atti Ctrl
ctrlpane.btn.help=Help
ctrlpane.btn.jointAnim=Joint Anim
ctrlpane.btn.objpos=Obj Pos
ctrlpane.btn.opengl=OpenGL
ctrlpane.btn.screen=Screen
ctrlpane.btn.sndAnalysis=Snd Anal
ctrlpane.label.adsHere=Ad Space
ctrlpane.title=Control Panel
attictrlpane.title=Attitude Control
attictrlpane.label.modeSelection=Mode Selection
attictrlpane.radio.manual=Manual
attictrlpane.btn.helpMessage.vts.start=Click the
attictrlpane.btn.helpMessage.vts.linkText=link
attictrlpane.btn.helpMessage.vts.end=to go
error.unableToOpenBrowser=Unable to open browser.