[package]
name = "gltf-reader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
easy-gltf = { version = "1.1.4", features = ["vertex-color", "names"] }
cgmath = "0.18"